name: form_validator
description: New Package to validate TextFormField .
version: 1.0.0
homepage: ''
repository: ''

environment:
  sdk: '>=2.17.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
