name: x_validation
description: New Package to validate TextFormField .
version: 1.0.0
homepage: https://pub.dev/packages/x_validation
repository: https://github.com/mazab99/x_validation

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  generate: true
  uses-material-design: true